// <auto-generated />
namespace LunarCoffee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _123 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_123));
        
        string IMigrationMetadata.Id
        {
            get { return "202305241726553_123"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
