// <auto-generated />
namespace LunarCoffee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update12062 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update12062));
        
        string IMigrationMetadata.Id
        {
            get { return "202304151442267_Update12062"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
